-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2019-11-23 14:45:41 EET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

---------------------------------------- CREARE TABELE SI CONSTRANGERI  --------------------------------------------------------

------------------------------------------------------- FOODS  -----------------------------------------------------------------
CREATE TABLE foods (
    food_id      NUMBER(4) NOT NULL,
    food_type    VARCHAR2(30),
    food_price   NUMBER(4)
)
LOGGING;

ALTER TABLE foods ADD CONSTRAINT foodprice_ck CHECK ( food_price > 10 );

ALTER TABLE foods ADD CONSTRAINT foods_pk PRIMARY KEY ( food_id );
--------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------- REGISTER  --------------------------------------------------------------
CREATE TABLE register (
    user_id      NUMBER(4) NOT NULL,
    first_name   VARCHAR2(30),
    last_name    VARCHAR2(30),
    username     VARCHAR2(30),
    password     VARCHAR2(30)
)
LOGGING;

ALTER TABLE register
    ADD CONSTRAINT firstname_ck CHECK ( length(first_name) > 1 );

ALTER TABLE register
    ADD CONSTRAINT lastname_ck CHECK ( length(last_name) > 1 );

ALTER TABLE register
    ADD CONSTRAINT username_ck CHECK ( length(username) > 5 );

ALTER TABLE register
    ADD CONSTRAINT password_ck CHECK ( length(password) > 5 );

ALTER TABLE register ADD CONSTRAINT register_pk PRIMARY KEY ( user_id );

--------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------- RESERVATION  -------------------------------------------------------------
CREATE TABLE reservation (
    res_id      NUMBER(4) NOT NULL,
    email       VARCHAR2(30),
    phone       VARCHAR2(30),
    check_in    DATE,
    check_out   DATE,
    user_id     NUMBER(4) NOT NULL,
    room_id     NUMBER(4) NOT NULL,
    food_id     NUMBER(4) NOT NULL,
    status_id   NUMBER(4) NOT NULL
)
LOGGING;

ALTER TABLE reservation
    ADD CONSTRAINT email_ck CHECK ( REGEXP_LIKE ( email,
                                                  '[a-z0-9._%-]+@[a-z0-9._%-]+\.[a-z]{2,4}' ) );


ALTER TABLE reservation
    ADD CONSTRAINT reservation_pk PRIMARY KEY (res_id);

ALTER TABLE reservation
    ADD CONSTRAINT relation_foods_res FOREIGN KEY ( food_id )
        REFERENCES foods ( food_id )
    NOT DEFERRABLE;

ALTER TABLE reservation
    ADD CONSTRAINT relation_reg_res FOREIGN KEY ( user_id )
        REFERENCES register ( user_id )
    NOT DEFERRABLE;

ALTER TABLE reservation
    ADD CONSTRAINT relation_rooms_res FOREIGN KEY ( room_id )
        REFERENCES rooms ( room_id )
    NOT DEFERRABLE;

ALTER TABLE reservation
    ADD CONSTRAINT relation_status_res FOREIGN KEY ( status_id )
        REFERENCES reservation_status ( status_id )
    NOT DEFERRABLE;

--------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------- RESERVATION STATUS  --------------------------------------------------------
CREATE TABLE reservation_status (
    status_id     NUMBER(4) NOT NULL,
    status_name   CHAR(1)
)
LOGGING;

ALTER TABLE reservation_status ADD CONSTRAINT status_pk PRIMARY KEY ( status_id );

--------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------- ROOMS  -----------------------------------------------------------------
CREATE TABLE rooms (
    room_id      NUMBER(4) NOT NULL,
    room_type    VARCHAR2(30),
    room_price   NUMBER(4)
)
LOGGING;

ALTER TABLE rooms ADD CHECK ( room_id BETWEEN 20 AND 40 );

ALTER TABLE rooms
    ADD CONSTRAINT roomtype_ck CHECK ( room_type IN (
        'DOUBLE',
        'FAMILY',
        'SINGLE'
    ) );

ALTER TABLE rooms ADD CONSTRAINT roomprice_ck CHECK ( room_price > 50 );

ALTER TABLE rooms ADD CONSTRAINT rooms_pk PRIMARY KEY ( room_id );
--------------------------------------------------------------------------------------------------------------------------------






